// Shared HTML+inline-SVG preview for any `scene.json` writer (scenegen’s `gen.mjs`, or diaggen
// after `toScene`). Regenerated by those pipelines; can also run standalone: `node preview.mjs [scene.json]`.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

// Visual-only preview styling.
// Keep strokes thin so geometry relationships are easier to inspect.
const PREVIEW_STROKE_WIDTH = 1.0;
const SVG_NON_SCALING_STROKE_ATTR = `vector-effect="non-scaling-stroke"`;

/**
 * Turn a scene model into a fixed-path HTML preview (inline SVG) for inspection.
 * Applies a y-flip so scene math coords (y up) map into SVG (y down).
 * v2 scenes require `scene.meta.previewFrame` (scene-space AABB).
 *
 * @param {object} scene
 * @param {string} outPath absolute or relative path to preview.html
 */
export function writePreviewHtml(scene, outPath) {
  mkdirSync(dirname(outPath), { recursive: true });
  const vb = computeViewBox(scene);
  const pad = 16; // total horizontal/vertical inset from viewport edges (8px each side)
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(String(scene.meta?.title ?? "preview"))}</title>
  <style>
    html, body { height: 100%; margin: 0; background: #fff; }
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      box-sizing: border-box;
      padding: ${pad / 2}px;
    }
    svg {
      display: block;
      flex-shrink: 0;
      width: min(calc(100vw - ${pad}px), calc((100vh - ${pad}px) * ${vb.vbW} / ${vb.vbH}));
      height: auto;
      max-height: calc(100vh - ${pad}px);
    }
  </style>
</head>
<body>
${sceneToSvgInline(scene, vb)}
</body>
</html>
`;
  writeFileSync(outPath, html, "utf8");
}

/** Padding inside viewBox units (scene pixels) around computed content. */
const VIEW_BOX_PAD = 10;

/**
 * Tight viewBox in root SVG coordinates so the preview scales to the diagram, not the full canvas.
 * Scene coords are y-up; root SVG uses y-down with `translate(0,canvasH) scale(1,-1)` on content.
 *
 * @param {object} scene
 * @returns {{ vbX: number, vbY: number, vbW: number, vbH: number, canvasH: number }}
 */
function computeViewBox(scene) {
  const w = Number(scene.meta?.width) || 400;
  const h = Number(scene.meta?.height) || 300;
  const useV2 =
    scene.version >= 2 && scene.root != null && scene.root.kind === "group";
  if (!useV2) {
    return { vbX: 0, vbY: 0, vbW: w, vbH: h, canvasH: h };
  }
  const pad = VIEW_BOX_PAD;
  const pf = scene.meta?.previewFrame;
  if (!isValidPreviewFrame(pf)) {
    throw new Error(
      "v2 scene.meta.previewFrame is required: { minX, maxX, minY, maxY } in scene space (use diagram contentBounds → toScene, or scenegen spec.previewFrame)",
    );
  }
  const vbX = pf.minX - pad;
  const vbY = h - pf.maxY - pad;
  const vbW = pf.maxX - pf.minX + 2 * pad;
  const vbH = pf.maxY - pf.minY + 2 * pad;
  return { vbX, vbY, vbW, vbH, canvasH: h };
}

/**
 * @param {unknown} pf
 * @returns {pf is { minX: number, maxX: number, minY: number, maxY: number }}
 */
function isValidPreviewFrame(pf) {
  if (pf == null || typeof pf !== "object") return false;
  const o = /** @type {Record<string, unknown>} */ (pf);
  const { minX, maxX, minY, maxY } = o;
  if (
    ![minX, maxX, minY, maxY].every(
      (v) => typeof v === "number" && Number.isFinite(v),
    )
  ) {
    return false;
  }
  return (
    /** @type {number} */ (maxX) - /** @type {number} */ (minX) > 1e-6 &&
    /** @type {number} */ (maxY) - /** @type {number} */ (minY) > 1e-6
  );
}

/**
 * @param {object} scene
 * @param {{ vbX: number, vbY: number, vbW: number, vbH: number, canvasH: number }} vb
 */
function sceneToSvgInline(scene, vb) {
  const w = Number(scene.meta?.width) || 400;
  const h = Number(scene.meta?.height) || 300;
  const useV2 =
    scene.version >= 2 && scene.root != null && scene.root.kind === "group";

  if (!useV2) {
    return legacySceneToSvg(scene, w, h);
  }

  const inner = renderNode(scene.root);
  const { vbX, vbY, vbW, vbH, canvasH } = vb;

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${vbW}" height="${vbH}" viewBox="${vbX} ${vbY} ${vbW} ${vbH}" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
  <g transform="translate(0,${canvasH}) scale(1,-1)">
${inner}
  </g>
</svg>`;
}

/** @param {import('./sceneModel.mjs').SceneNode} node */
function renderNode(node) {
  switch (node.kind) {
    case "group": {
      const body = node.children.map((c) => renderNode(c)).join("\n    ");
      return `    <g data-name="${escapeAttr(node.name)}">\n    ${body}\n    </g>`;
    }
    case "line": {
      const { start: a, end: b } = node;
      return `    <line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="#334" stroke-width="${PREVIEW_STROKE_WIDTH}" ${SVG_NON_SCALING_STROKE_ATTR} fill="none" />`;
    }
    case "arc": {
      if (node.facetedPreview === true) {
        const pts = circularArcToFacetedPoints(
          node.center,
          node.start,
          node.sweepRad,
        );
        if (pts === "") return "";
        return `    <polyline points="${escapeAttr(pts)}" stroke="#335" stroke-width="${PREVIEW_STROKE_WIDTH}" ${SVG_NON_SCALING_STROKE_ATTR} fill="none" stroke-linejoin="round" stroke-linecap="round" />`;
      }
      const d = circularArcToPathD(node.center, node.start, node.sweepRad);
      return `    <path d="${escapeAttr(d)}" stroke="#335" stroke-width="${PREVIEW_STROKE_WIDTH}" ${SVG_NON_SCALING_STROKE_ATTR} fill="none" shape-rendering="geometricPrecision" />`;
    }
    case "triangle": {
      const { a, b, c } = node;
      const pts = `${a.x},${a.y} ${b.x},${b.y} ${c.x},${c.y}`;
      const fillAttr = node.outline ? 'none' : '#335';
      return `    <polygon points="${escapeAttr(pts)}" fill="${fillAttr}" stroke="#335" stroke-width="${PREVIEW_STROKE_WIDTH}" ${SVG_NON_SCALING_STROKE_ATTR} />`;
    }
    case "circle": {
      const { center, radius } = node;
      return `    <circle cx="${center.x}" cy="${center.y}" r="${radius}" fill="#335" stroke="#335" stroke-width="${PREVIEW_STROKE_WIDTH}" ${SVG_NON_SCALING_STROKE_ATTR} />`;
    }
    case "text": {
      return renderTextSvg(node);
    }
    default:
      return "";
  }
}

const PI_TOL = 1e-9;

/**
 * Sample a circular arc in scene space (y up, CCW sweep) for `<polyline points="...">`.
 * Avoids SVG `A`; useful to isolate preview bugs in elliptical-arc flag handling.
 *
 * @returns {string} space-separated "x,y" pairs, or "" if degenerate
 */
function circularArcToFacetedPoints(center, start, sweepRad) {
  const r = Math.hypot(start.x - center.x, start.y - center.y);
  if (r < 1e-9) return "";
  const a0 = Math.atan2(start.y - center.y, start.x - center.x);
  const n = Math.max(
    16,
    Math.ceil((32 * Math.abs(sweepRad)) / (2 * Math.PI)),
  );
  const parts = [];
  for (let i = 0; i <= n; i++) {
    const t = i / n;
    const a = a0 + sweepRad * t;
    parts.push(
      `${center.x + r * Math.cos(a)},${center.y + r * Math.sin(a)}`,
    );
  }
  return parts.join(" ");
}

/**
 * One SVG elliptical-arc segment (rx = ry = r). Scene space: y up, CCW positive sweep.
 *
 * @param {boolean} moveToStart if true, prefix with `M start`; if false, continue current subpath (chained `A`).
 */
function ellipseArcSegmentD(center, start, sweepRad, moveToStart) {
  const r = Math.hypot(start.x - center.x, start.y - center.y);
  if (r < 1e-9) return "";
  const a0 = Math.atan2(start.y - center.y, start.x - center.x);
  const x0 = start.x;
  const y0 = start.y;
  const a1 = a0 + sweepRad;
  const x1 = center.x + r * Math.cos(a1);
  const y1 = center.y + r * Math.sin(a1);
  const largeArc = Math.abs(sweepRad) > Math.PI ? 1 : 0;
  const sweep = sweepRad >= 0 ? 1 : 0;
  const prefix = moveToStart ? `M ${x0} ${y0} ` : "";
  return `${prefix}A ${r} ${r} 0 ${largeArc} ${sweep} ${x1} ${y1}`;
}

/**
 * Circular arc as SVG path `d` (scene space, y up, CCW positive).
 * Precedent for all circular arcs in preview: native `A`, never polyline approximation.
 *
 * For a **π** sweep, SVG’s `A` command is ambiguous (two equal-length semicircles between the
 * same endpoints; `large-arc` does not disambiguate at exactly 180°). Browsers may pick the
 * hemisphere whose bulge points opposite the intended direction. Splitting into two **π/2**
 * segments forces the minor arc at each step and matches the tide TimePointer spec (bulge through
 * local +X after placement).
 *
 * @param {{ x: number, y: number }} center
 * @param {{ x: number, y: number }} start
 * @param {number} sweepRad signed angle in radians (CCW)
 */
function circularArcToPathD(center, start, sweepRad) {
  const r = Math.hypot(start.x - center.x, start.y - center.y);
  if (r < 1e-9) return "";
  if (Math.abs(Math.abs(sweepRad) - Math.PI) < PI_TOL) {
    const half = sweepRad / 2;
    const a0 = Math.atan2(start.y - center.y, start.x - center.x);
    const mid = {
      x: center.x + r * Math.cos(a0 + half),
      y: center.y + r * Math.sin(a0 + half),
    };
    const first = ellipseArcSegmentD(center, start, half, true);
    const second = ellipseArcSegmentD(center, mid, half, false);
    return `${first} ${second}`;
  }
  return ellipseArcSegmentD(center, start, sweepRad, true);
}

/** @param {import('./sceneModel.mjs').TextPrimitive} node */
function renderTextSvg(node) {
  const { anchor, content, size, hAlign, angleRad } = node;
  const ax = anchor.x;
  const ay = anchor.y;
  const anchorAttr = textAnchorFor(hAlign);
  const deg = (-angleRad * 180) / Math.PI;
  const inner = escapeHtml(content);
  // Scene→SVG uses scale(1,-1) on the root; that flips glyph outlines. A local scale(1,-1)
  // around the anchor restores upright text without changing the anchor position.
  return `    <g transform="translate(${ax}, ${ay}) scale(1,-1) translate(${-ax}, ${-ay})">
      <g transform="rotate(${deg}, ${ax}, ${ay})">
      <text x="${ax}" y="${ay}" font-size="${size}" fill="#223" text-anchor="${anchorAttr}" dominant-baseline="alphabetic" font-family="ui-monospace, SFMono-Regular, Menlo, Consolas, monospace">${inner}</text>
      </g>
    </g>`;
}

/** @param {'left'|'center'|'right'} h */
function textAnchorFor(h) {
  if (h === "left") return "start";
  if (h === "right") return "end";
  return "middle";
}

/** v1 scene.json: `elements` rects in SVG coordinates (no y-flip). */
function legacySceneToSvg(scene, w, h) {
  const rects = (scene.elements ?? []).filter((e) => e.kind === "rect");
  const rectsSvg = rects
    .map(
      (r) =>
        `<rect x="${r.x}" y="${r.y}" width="${r.width}" height="${r.height}" fill="#e8eef5" stroke="#334" stroke-width="1" ${SVG_NON_SCALING_STROKE_ATTR} />`,
    )
    .join("\n    ");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
  ${rectsSvg}
</svg>`;
}

function escapeHtml(s) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function escapeAttr(s) {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;");
}

const isMain =
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const scenePath =
    process.argv[2] ?? join(__dirname, "generated", "scene.json");
  const outPath = join(__dirname, "generated", "preview.html");
  const scene = JSON.parse(readFileSync(scenePath, "utf8"));
  writePreviewHtml(scene, outPath);
  console.error(`Wrote ${outPath}`);
}
